version: '3'
services:
  zookeeper-server:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/x86_64
    networks: 
      - kafka-broker-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-server:
    image: confluentinc/cp-kafka:latest
    platform: linux/x86_64
    networks: 
      - kafka-broker-network
    depends_on:
      - zookeeper-server
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  kaka-connect-server:
    image: debezium/connect
    platform: linux/x86_64
    networks: 
      - kafka-broker-network
    depends_on:
      - kafka-server
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connector_config_topic
      OFFSET_STORAGE_TOPIC: debezium_connector_offsets_topic
      BOOTSTRAP_SERVERS: kafka-server:29092

  kafka-connect-ui:
    image: debezium/debezium-ui
    platform: linux/x86_64
    networks: 
      - kafka-broker-network
    depends_on:
      - kaka-connect-server
    ports:
      - 8080:8080
    environment:
      KAFKA_CONNECT_URIS: http://kaka-connect-server:8083

networks: 
  kafka-broker-network:
    external: true
    name:  kafka-broker-network
    driver: bridge 