version: '3'
services:
  sales-db:
    image: mysql
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 1234MySql
      MYSQL_DATABASE: db_sales
    ports:
      - 3306:3306

networks: 
  default:
    external:
      name: platform_network