version: '3'
services:

  ############################################# Sessão contendo a estrutura que simula cloud para podermos construir o cenário de armazenamento ##############################################
  
  localstack-server:
    container_name: "localstack-server"
    image: localstack/localstack
    platform: linux/x86_64
    hostname: aws.localstack.docker
    ports:
      - "127.0.0.1:4510-4559:4510-4559" 
      - "127.0.0.1:4566:4566"
    environment:
      - LOCALSTACK_SERVICES=s3
      - DEBUG=1
      - DATA_DIR=./tmp/localstack-data/
      - HOST_TMP_FOLDER=./tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


  ############################################# Sessão contendo a estrutura Kafka para Data Acquisition ##############################################
  zookeeper-server:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/x86_64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-server:
    image: confluentinc/cp-kafka:latest
    platform: linux/x86_64
    depends_on:
      - zookeeper-server
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  kaka-connect-server:
    image: debezium/connect
    platform: linux/x86_64
    depends_on:
      - kafka-server
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connector_config_topic
      OFFSET_STORAGE_TOPIC: debezium_connector_offsets_topic
      BOOTSTRAP_SERVERS: kafka-server:29092

  kafka-connect-ui:
    image: debezium/debezium-ui:1.9.3.Final
    platform: linux/x86_64
    depends_on:
      - kaka-connect-server
    ports:
      - 8085:8080
    environment:
      KAFKA_CONNECT_URIS: http://kaka-connect-server:8083
      DEPLOYMENT_MODE: validation_disabled

  ####################################################################################################################################################

networks: 
  default:
    external:
      name: platform_network
